"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
import certifi

from .email_ssl_patch import patch_smtp_ssl
patch_smtp_ssl()


BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# BASIC SETTINGS
# ---------------------------

SECRET_KEY = 'django-insecure-@y^kfkzmp@3d*o$#9wh2uq5*j^!w7#zki=#2ykfv$&3p1(7v3!'
DEBUG = True
ALLOWED_HOSTS = []

# ---------------------------
# APPS
# ---------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.pages',
    'apps.users',
    'apps.membership',
    'apps.schedule',
    'apps.bookings',
    'apps.trainers',
]

# ---------------------------
# MIDDLEWARE
# ---------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# ---------------------------
# TEMPLATES
# ---------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ---------------------------
# DATABASE
# ---------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------
# PASSWORD VALIDATION
# ---------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ---------------------------
# INTERNATIONALIZATION
# ---------------------------

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('kk', 'Kazakh'),
    ('ru', 'Russian'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

USE_I18N = True
TIME_ZONE = 'UTC'
USE_TZ = True

# ---------------------------
# STATIC FILES
# ---------------------------

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------
# CUSTOM USER MODEL
# ---------------------------

AUTH_USER_MODEL = "users.User"

# ---------------------------
# EMAIL — Gmail SMTP
# ---------------------------


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "kukakamakaka99@gmail.com"
EMAIL_HOST_PASSWORD = "uvlp vokz ftmy hlnh"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
