# Generated by Django 5.2.8 on 2025-12-02 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='monthly_trainings',
            field=models.PositiveIntegerField(default=0, help_text='Тренировок за текущий месяц'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0, help_text='Серия тренировки (сколько дней подряд клиент посещает занятия)'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='total_trainings',
            field=models.PositiveIntegerField(default=0, help_text='Всего тренировок за весь период'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата последнего обновления профиля'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Фото профиля', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения клиента', null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания профиля'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Женский'), ('male', 'Мужской'), ('other', 'Другое')], help_text='Пол клиента', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон клиента', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
