# Generated by Django 5.2.8 on 2025-12-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('yoga', 'Йога'), ('boxing', 'Бокс'), ('crossfit', 'Кроссфит'), ('hiit', 'HIIT'), ('strength', 'Силовая'), ('personal', 'Персональная тренировка')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_clients', models.IntegerField(default=10)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='trainers.trainer')),
            ],
        ),
    ]
